package chap7.d4EncapsulatingDataWithRecords.page398;

//Applying Pattern Matching Records to Switch
//It might not be a surprise that you can use switch with pattern matching and records. The rules are the same as you’ve already learned, we’re just combing the switch pattern matching rules you learned about in Chapter 3 with what we covered in this chapter.
//        Let’s say we have a Snake record as follows:
record Snake(Object data) {
//    long showData(Snake snake) {}
    //Next, let’s construct a method that operates on an instance of Snake.
    long showData(Snake snake) {
        return switch (snake) {
            case Snake(Long hiss) -> hiss + 1;
            case Snake(Integer nagina) -> nagina + 10;
            case Snake(Number crowley) -> crowley.intValue() + 100;
            case Snake(Object kaa) -> -1;
        };
    }
}

//As you might recall from Chapter 3, a default clause is not required if all types are covered in the pattern matching expression. Given this code, see if you can follow the output generated by each of these examples:
public class Page398{
    public static void main(String[] args) {
        var s = new Snake("CobraKi");

        System.out.println(s.showData(new Snake(1)));    // 11
        System.out.println(s.showData(new Snake(2L)));   // 3
        System.out.println(s.showData(new Snake(3.0)));  // 103

    }
}
//
//Remember, the type matters for any associated when clauses. For example, the following does not compile since kaa is of type Object, which does not have a doubleValue() method:
//long showData(Snake snake) {
//    return switch(snake) {
//        case Snake(Object kaa) when kaa.doubleValue() > 0 -> -1;
//        default -> 1_000;
//    };
//}
//
//Congrats, you’ve learned everything you need to know about pattern matching with records for the exam. Since it’s a new feature, expect to see at least one question on it!
